# Generated by Django 4.1.7 on 2025-02-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Ожидает обработки', max_length=50),
        ),
    ]
