# Generated by Django 4.1.7 on 2025-02-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='adress',
            field=models.CharField(default='Не добавлен', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='first_name',
            field=models.CharField(default='Не добавлен', max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='surname',
            field=models.CharField(default='Не добавлен', max_length=255, verbose_name='Фамилия'),
        ),
    ]
