# Generated by Django 4.1.7 on 2025-02-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_shopuser_first_name_alter_shopuser_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='adress',
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(default='Не указан', max_length=20, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='Не указан', max_length=20, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='Не указана', max_length=255, verbose_name='Улица'),
        ),
    ]
