# Generated by Django 4.1.7 on 2025-02-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_city_alter_order_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='house',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='street',
        ),
    ]
